apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-deployment
  labels:
    app: docker-trace-fib
spec:
  selector:
    matchLabels:
      app: docker-trace-fib
  template:
    metadata:
      labels:
        app: docker-trace-fib
    spec:
      containers:
        - name: docker-trace
          image: localhost:32000/docker-trace
          ports:
            - containerPort: 9090